# Generated by Django 2.2.4 on 2019-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20191018_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ('prato',)},
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='lista_pedidos',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='acompanhamentos',
            field=models.CharField(choices=[('', 'Selecione'), ('Banana frita, linguiça, ovo, couve (virado)', 'Banana frita, linguiça, ovo, couve (virado)'), ('Legumes refogados', 'Legumes refogados'), ('Escarola', 'Escarola'), ('Fritas', 'Fritas')], default='Selecione', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='prato',
            field=models.CharField(choices=[('', 'Selecione'), ('Virado a Paulista', 'Virado a Paulista'), ('Bife', 'Bife'), ('Filé de frango', 'Filé de frango'), ('Frango ao molho', 'Frango ao molho'), ('Carne de panela', 'Carne de panela'), ('Figado acebolado', 'Figado acebolado'), ('Bife acebolado', 'Bife acebolado'), ('Feijoada', 'Feijoada'), ('Calabresa', 'Calabresa')], default='Selecione', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='saladas',
            field=models.CharField(choices=[('', 'Selecione'), ('Alface e pepino', 'Alface e pepino'), ('Repolho e cenoura', 'Repolho e cenoura')], default='Selecione', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('', 'Selecione'), ('Dinheiro', 'Dinheiro'), ('Cartão', 'Debito'), ('Cartão', 'Credito')], default='Selecione', max_length=20),
        ),
    ]
