# Generated by Django 2.1.2 on 2019-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20191121_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='acompanhamentos',
            field=models.CharField(choices=[('', 'Selecione'), ('Banana Frita', 'Banana Frita'), ('Linguça', 'Linguiça'), ('Ovo', 'Ovo'), ('Couve(virado)', 'Couve(virado)'), ('Legumes refogados', 'Legumes refogados'), ('Escarola', 'Escarola'), ('Fritas', 'Fritas')], default='Selecione', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
    ]
