# Generated by Django 2.1.2 on 2019-12-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20191206_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='observacoes',
            field=models.CharField(max_length=2000, null=True, verbose_name='observações'),
        ),
    ]
